services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres2
      - POSTGRES_PASSWORD=Test123
      - POSTGRES_DB=DbCatalog
    restart: always
    ports:
        
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/ 
    

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Host=catalogdb;Port=5432;Database=DbCatalog;Username=postgres2;Password=Test123
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
